# Generated by Django 5.2.7 on 2025-10-18 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0004_tbl_type'),
        ('Guest', '0006_tbl_advocate_advocate_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(max_length=30)),
                ('case_section', models.CharField(max_length=100)),
                ('case_content', models.CharField(max_length=300)),
                ('case_file', models.FileField(upload_to='Assets/Files/Case')),
                ('case_datetime', models.DateTimeField(auto_now_add=True)),
                ('policestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_policestation')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_type')),
            ],
        ),
    ]
