# Generated by Django 5.2.7 on 2025-10-20 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PoliceStation', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_case',
        ),
    ]
