# Generated by Django 5.2.7 on 2025-10-20 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0006_tbl_advocate_advocate_status_and_more'),
        ('PoliceStation', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_casedesc', models.CharField(max_length=50)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('advocate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_advocate')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PoliceStation.tbl_case')),
            ],
        ),
    ]
