# Generated by Django 5.2.7 on 2025-10-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advocate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_request',
            name='request_status',
            field=models.IntegerField(default=0),
        ),
    ]
