# Generated by Django 5.2.7 on 2025-10-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advocate', '0002_tbl_request_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_request',
            name='request_bailfile',
            field=models.FileField(blank=True, null=True, upload_to='bail_files/'),
        ),
    ]
