# Generated by Django 5.2.7 on 2025-10-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advocate', '0003_tbl_request_request_bailfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_request',
            name='request_bailfile',
            field=models.FileField(blank=True, null=True, upload_to='Assets/BailFiles/'),
        ),
    ]
