# Generated by Django 5.2.5 on 2025-09-12 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_tbl_place'),
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_policestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policestation_name', models.CharField(max_length=40)),
                ('policestation_email', models.CharField(max_length=40)),
                ('policestation_contact', models.CharField(max_length=40)),
                ('policestation_address', models.CharField(max_length=40)),
                ('policestation_password', models.CharField(max_length=40)),
                ('policestation_photo', models.FileField(upload_to='Assets/Police/Photo/')),
                ('policestation_proof', models.FileField(upload_to='Assets/Police/Proof')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
