# Generated by Django 5.0.2 on 2025-09-13 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_tbl_place'),
        ('Guest', '0002_tbl_policestation'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb1_advocate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advocate_name', models.CharField(max_length=40)),
                ('advocate_email', models.CharField(max_length=40)),
                ('advocate_contact', models.CharField(max_length=40)),
                ('advocate_address', models.CharField(max_length=40)),
                ('advocate_password', models.CharField(max_length=40)),
                ('advocate_photo', models.CharField(max_length=40)),
                ('advocate_proof', models.CharField(max_length=40)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
