# Generated by Django 5.2.5 on 2025-09-21 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_tbl_place'),
        ('Guest', '0003_tb1_advocate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tb1_advocate',
            new_name='tbl_advocate',
        ),
    ]
