# Generated by Django 5.2.5 on 2025-09-22 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_rename_tb1_advocate_tbl_advocate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_advocate',
            name='advocate_photo',
            field=models.FileField(upload_to='Assets/Advocate/photo/'),
        ),
        migrations.AlterField(
            model_name='tbl_advocate',
            name='advocate_proof',
            field=models.FileField(upload_to='Assets/Advocate/photo'),
        ),
    ]
