# Generated by Django 5.2.5 on 2025-10-11 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_alter_tbl_advocate_advocate_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_advocate',
            name='advocate_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tbl_policestation',
            name='police_status',
            field=models.IntegerField(default=0),
        ),
    ]
