# Generated by Django 5.2.5 on 2025-10-11 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0006_tbl_advocate_advocate_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('booking_status', models.IntegerField(default=0)),
                ('booking_todate', models.DateField(auto_now_add=True)),
                ('booking_content', models.CharField(max_length=150)),
                ('booking_file', models.FileField(upload_to='Assets/User/file')),
                ('booking_amount', models.CharField(max_length=40)),
                ('advocate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_advocate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
