# Generated by Django 5.2.7 on 2025-10-17 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0006_tbl_advocate_advocate_status_and_more'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_content', models.CharField(max_length=500)),
                ('chat_time', models.DateTimeField()),
                ('chat_file', models.FileField(upload_to='ChatFiles/')),
                ('advocate_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advocate_from', to='Guest.tbl_advocate')),
                ('advocate_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advocate_to', to='Guest.tbl_advocate')),
                ('user_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_from', to='Guest.tbl_user')),
                ('user_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_to', to='Guest.tbl_user')),
            ],
        ),
    ]
