# Generated by Django 5.2.7 on 2025-10-20 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_tbl_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_booking',
            name='booking_todate',
        ),
    ]
