# Generated by Django 5.2.7 on 2025-10-20 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0006_tbl_advocate_advocate_status_and_more'),
        ('User', '0004_complaint'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='complaint',
            new_name='tbl_complaint',
        ),
    ]
